---
version: '3'
services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_URL=http://localhost:8080
    volumes:
      - ./keycloak/data/test-realm.json:/opt/keycloak/data/import/test-realm.json:ro
      - ./keycloak/data/test-users-0.json:/opt/keycloak/data/import/test-users-0.json:ro
    command: ["start-dev", "--import-realm"]
  